language: java
jdk:
  - oraclejdk8
branches:
  only:
    - develop
    - develop-test # test only
script:
  - mvn install -Dmaven.javadoc.skip=true -Dkotlin.compile.incremental=false # one only
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.m2
