language: java
jdk:
  - openjdk8
branches:
  only:
    - master
    - develop
script:
  - mvn install -Dmaven.javadoc.skip=true -Dkotlin.compile.incremental=true
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.m2
